
CREATE TABLE store_orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id NUMBER REFERENCES orders(id) ON DELETE CASCADE,
  store_id VARCHAR2(24) NOT NULL,
  status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'shipped', 'delivered','cancelled')),
  payment_amount NUMBER,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
