CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(24) NOT NULL,
    cart_id VARCHAR2(24) NOT NULL,
    status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'shipped', 'delivered')),
    shipping_address VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    payment_mode VARCHAR2(20) DEFAULT 'cod' CHECK (payment_mode IN ('cod', 'online'))
);
